import { Country } from './country';

export const COUNTRIES: Country[] = [
    { id: 'AFGHANISTAN', name: 'Afghanistan', capital: 'Kabul', imageUrl: 'images/afghanistan.jpeg', isVisited: false },
    { id: 'ALBANIA', name: 'Albania', capital: 'Tirana (Tirane)', imageUrl: 'images/albania.jpeg', isVisited: false },
    { id: 'ALGERIA', name: 'Algeria', capital: 'Algiers', imageUrl: 'images/algeria.jpeg', isVisited: false },
    { id: 'ANDORRA', name: 'Andorra', capital: 'Andorra la Vella', imageUrl: 'images/andorra.jpeg', isVisited: false },
    { id: 'ANGOLA', name: 'Angola', capital: 'Luanda', imageUrl: 'images/angola.jpeg', isVisited: false },
    { id: 'ANTIGUA_AND_BARBUDA', name: 'Antigua and Barbuda', capital: 'Saint John\'s',
      imageUrl: 'images/antigua_and_barbuda.jpeg', isVisited: false },
    { id: 'ARGENTINA', name: 'Argentina', capital: 'Bueos Aires', imageUrl: 'images/argentina.jpeg', isVisited: false },
    { id: 'ARMENIA', name: 'Armenia', capital: 'Yerevan', imageUrl: 'images/armenia.jpeg', isVisited: false },
    { id: 'AUSTRALIA', name: 'Australia', capital: 'Canberra', imageUrl: 'images/australia.jpeg', isVisited: false },
    { id: 'AUSTRIA', name: 'Austria', capital: 'Vienna', imageUrl: 'images/austria.jpeg', isVisited: false },
    { id: 'AZERBAIJAN', name: 'Azerbaijan', capital: 'Baku', imageUrl: 'images/azerbaijan.jpeg', isVisited: false },
    { id: 'BAHAMAS', name: 'Bahamas', capital: 'Nassau', imageUrl: 'images/bahamas.jpeg', isVisited: false },
    { id: 'BAHRAIN', name: 'Bahrain', capital: 'Manama', imageUrl: 'images/bahrain.jpeg', isVisited: false },
    { id: 'BANGLADESH', name: 'Bangladesh', capital: 'Dhaka', imageUrl: 'images/bangladesh.jpeg', isVisited: false },
    { id: 'BARBADOS', name: 'Barbados', capital: 'Bridgetown', imageUrl: 'images/barbados.jpeg', isVisited: false },
    { id: 'BELARUS', name: 'Belarus', capital: 'Minsk', imageUrl: 'images/belarus.jpeg', isVisited: false },
    { id: 'BELGIUM', name: 'Belgium', capital: 'Brussels', imageUrl: 'images/belgium.jpeg', isVisited: false },
    { id: 'BELIZE', name: 'Belize', capital: 'Belmopan', imageUrl: 'images/belize.jpeg', isVisited: false },
    { id: 'BENIN', name: 'Benin', capital: 'Porto Novo', imageUrl: 'images/benin.jpeg', isVisited: false },
    { id: 'BHUTAN', name: 'Bhutan', capital: 'Thimpu', imageUrl: 'images/bhutan.jpeg', isVisited: false },
    { id: 'BOLIVIA', name: 'Bolivia', capital: 'La Paz (administrative), Sucre (official)',
      imageUrl: 'images/bolivia.jpeg', isVisited: false },
    { id: 'BOSNIA_AND_HERZEGOVINA', name: 'Bosnia and Herzegovina', capital: 'Sarajevo',
      imageUrl: 'images/bosnia_and_herzegovina.jpeg', isVisited: false },
    { id: 'BOTSWANA', name: 'Botswana', capital: 'Gaborone', imageUrl: 'images/botswana.jpeg', isVisited: false },
    { id: 'BRAZIL', name: 'Brazil', capital: 'Brasilia', imageUrl: 'images/brazil.jpeg', isVisited: false },
    { id: 'BRUNEI', name: 'Brunei', capital: 'Bandar Seri Begawan', imageUrl: 'images/brunei.jpeg', isVisited: false },
    { id: 'BULGARIA', name: 'Bulgaria', capital: 'Sofia', imageUrl: 'images/bulgaria.jpeg', isVisited: false },
    { id: 'BURKINA_FASO', name: 'Burkunia Faso', capital: 'Ouagadougou', imageUrl: 'images/burkina_faso.jpeg', isVisited: false },
    { id: 'BURUNDI', name: 'Burundi', capital: 'Gitega', imageUrl: 'images/burundi.jpeg', isVisited: false },
    { id: 'CAMBODIA', name: 'Cambodia', capital: 'Phnom Penh', imageUrl: 'images/cambodia.jpeg', isVisited: false },
    { id: 'CAMEROON', name: 'Cameroon', capital: 'Yaounde', imageUrl: 'images/cameroon.jpeg', isVisited: false },
    { id: 'CANADA', name: 'Canada', capital: 'Ottawa', imageUrl: 'images/canada.jpeg', isVisited: false },
    { id: 'CAPE_VERDE', name: 'Cape Verde', capital: 'Praia', imageUrl: 'images/cape_verde.jpeg', isVisited: false },
    { id: 'CENTRAL_AFRICAN_REPUBLIC', name: 'Central African Republic', capital: 'Bangui',
      imageUrl: 'images/central_african_republic.jpeg', isVisited: false },
    { id: 'CHAD', name: 'Chad', capital: 'N\'Djamena', imageUrl: 'images/chad.jpeg', isVisited: false },
    { id: 'CHILE', name: 'Chile', capital: 'Santiago', imageUrl: 'images/chile.jpeg', isVisited: false },
    { id: 'CHINA', name: 'China', capital: 'Beijing', imageUrl: 'images/china.jpeg', isVisited: false },
    { id: 'COLOMBIA', name: 'Colombia', capital: 'Bogota', imageUrl: 'images/colombia.jpeg', isVisited: false },
    { id: 'COMOROS', name: 'Comoros', capital: 'Moroni', imageUrl: 'images/comoros.jpeg', isVisited: false },
    { id: 'CONGO_DEMOCRATIC_REPUBLIC_OF_THE', name: 'Congo, Democratic Republic of the', capital: 'Kinshasa',
      imageUrl: 'images/congo_democratic_republic_of_the.jpeg', isVisited: false },
    { id: 'CONGO_REPUBLIC_OF_THE', name: 'Congo, Republic of the', capital: 'Brazzaville',
      imageUrl: 'images/congo_republic_of_the.jpeg', isVisited: false },
    { id: 'COSTA_RICA', name: 'Costa Rica', capital: 'San Jose', imageUrl: 'images/costa_rica.jpeg', isVisited: false },
    { id: 'COTE_DLVOIRE', name: 'Côte d\'lvoire (Ivory Coast)', capital: 'Yamoussoukro',
      imageUrl: 'images/cote_dlvoire.jpeg', isVisited: false },
    { id: 'CROATIA', name: 'Croatia', capital: 'Zagreb', imageUrl: 'images/croatia.jpeg', isVisited: false },
    { id: 'CUBA', name: 'Cuba', capital: 'Havana', imageUrl: 'images/cuba.jpeg', isVisited: false },
    { id: 'CYPRUS', name: 'Cyprus', capital: 'Nicosia', imageUrl: 'images/cyprus.jpeg', isVisited: false },
    { id: 'CZECH_REPUBLIC ', name: 'Czech Republic (Czechia)', capital: 'Prague',
      imageUrl: 'images/czech_republic.jpeg', isVisited: false },
    { id: 'DENMARK ', name: 'Denmark', capital: 'Copenhagen', imageUrl: 'images/denmark.jpeg', isVisited: false },
    { id: 'DJIBOUTI ', name: 'Djibouti', capital: 'Djibouti', imageUrl: 'images/djibouti.jpeg', isVisited: false },
    { id: 'DOMINCIA ', name: 'Domincia', capital: 'Roseau', imageUrl: 'images/domincia.jpeg', isVisited: false },
    { id: 'DOMINICAN_REPUBLIC ', name: 'Dominican Republic', capital: 'Santo Domingo',
      imageUrl: 'images/dominican_republic.jpeg', isVisited: false },
    { id: 'EAST_TIMOR ', name: 'East Timor', capital: 'Dili', imageUrl: 'images/east_timor.jpeg', isVisited: false },
    { id: 'ECUADOR ', name: 'Ecuador', capital: 'Quito', imageUrl: 'images/ecuador.jpeg', isVisited: false },
    { id: 'EGYPT ', name: 'Egypt', capital: 'Cairo', imageUrl: 'images/egypt.jpeg', isVisited: false },
    { id: 'EL_SALVADOR ', name: 'El Salvador', capital: 'San Salvador', imageUrl: 'images/el_salvador.jpeg', isVisited: false },
    { id: 'ENGLAND ', name: 'England', capital: 'London', imageUrl: 'images/england.jpeg', isVisited: false },
    { id: 'EQUATORIAL_GUINEA ', name: 'Equatorial Guinea', capital: 'Malabo', imageUrl: 'images/equatorial_guinea.jpeg', isVisited: false },
    { id: 'ERITREA ', name: 'Eritrea', capital: 'Asmara', imageUrl: 'images/eritrea.jpeg', isVisited: false },
    { id: 'ESTONIA ', name: 'Estonia', capital: 'Tallinn', imageUrl: 'images/estonia.jpeg', isVisited: false },
    { id: 'ESWATINI ', name: 'Eswatini (Swaziland)', capital: 'Mbabana', imageUrl: 'images/eswatini.jpeg', isVisited: false },
    { id: 'ETHIOPIA ', name: 'Ethiopia', capital: 'Addis Ababa', imageUrl: 'images/ethiopia.jpeg', isVisited: false },
    { id: 'FEDERATED_STATES_OF_MICRONESIA ', name: 'Federated States of Micronesia', capital: 'Palikir',
      imageUrl: 'images/federal_states_of_micronesia.jpeg', isVisited: false },
    { id: 'FIJI ', name: 'Fiji', capital: 'Suva', imageUrl: 'images/fiji.jpeg', isVisited: false },
    { id: 'FINLAND ', name: 'Finland', capital: 'Helsinki', imageUrl: 'images/finland.jpeg', isVisited: false },
    { id: 'FRANCE ', name: 'France', capital: 'Paris', imageUrl: 'images/france.jpeg', isVisited: false },
    { id: 'GABON ', name: 'Gabon', capital: 'Libreville', imageUrl: 'images/gabon.jpeg', isVisited: false },
    { id: 'GAMBIA ', name: 'Gambia', capital: 'Banjul', imageUrl: 'images/gambia.jpeg', isVisited: false },
    { id: 'GEORGIA ', name: 'Georgia', capital: 'Tbilisi', imageUrl: 'images/georgia.jpeg', isVisited: false },
    { id: 'GERMANY ', name: 'Germany', capital: 'Berlin', imageUrl: 'images/germany.jpeg', isVisited: false },
    { id: 'GHANA ', name: 'Ghana', capital: 'Accra', imageUrl: 'images/ghana.jpeg', isVisited: false },
    { id: 'GREECE ', name: 'Greece', capital: 'Athens', imageUrl: 'images/greece.jpeg', isVisited: false },
    { id: 'GRENADA ', name: 'Grenada', capital: 'Saint George\'s', imageUrl: 'images/grenada.jpeg', isVisited: false },
    { id: 'GUATEMALA ', name: 'Guatemala', capital: 'Guatemala City', imageUrl: 'images/guatemala.jpeg', isVisited: false },
    { id: 'GUINEA ', name: 'Guinea', capital: 'Conakry', imageUrl: 'images/guinea.jpeg', isVisited: false },
    { id: 'GUINEA_BISSAU ', name: 'Guinea-Bissau', capital: 'Bissau', imageUrl: 'images/guinea_bissau.jpeg', isVisited: false },
    { id: 'GUYANA ', name: 'Guyana', capital: 'Georgetown', imageUrl: 'images/guyana.jpeg', isVisited: false },
    { id: 'HAITI ', name: 'Haiti', capital: 'Port au Prince', imageUrl: 'images/haiti.jpeg', isVisited: false },
    { id: 'HONDURAS ', name: 'Honduras', capital: 'Tegucigalpa', imageUrl: 'images/honduras.jpeg', isVisited: false },
    { id: 'HUNGARY ', name: 'Hungary', capital: 'Budapest', imageUrl: 'images/hungary.jpeg', isVisited: false },
    { id: 'ICELAND ', name: 'Iceland', capital: 'Reykjavik', imageUrl: 'images/iceland.jpeg', isVisited: false },
    { id: 'INDIA ', name: 'India', capital: 'New Delhi', imageUrl: 'images/india.jpeg', isVisited: true },
    { id: 'INDONESIA ', name: 'Indonesia', capital: 'Jakarta', imageUrl: 'images/indonesia.jpeg', isVisited: false },
    { id: 'IRAN ', name: 'Iran', capital: 'Tehran', imageUrl: 'images/iran.jpeg', isVisited: false },
    { id: 'IRAQ ', name: 'Iraq', capital: 'Baghdad', imageUrl: 'images/iraq.jpeg', isVisited: false },
    { id: 'IRELAND ', name: 'Ireland', capital: 'Dublin', imageUrl: 'images/ireland.jpeg', isVisited: false },
    { id: 'ISRAEL ', name: 'Israel', capital: 'Jerusalem', imageUrl: 'images/israel.jpeg', isVisited: false },
    { id: 'ITALY ', name: 'Italy', capital: 'Rome', imageUrl: 'images/italy.jpeg', isVisited: false },
    { id: 'JAMAICA ', name: 'Jamaica', capital: 'Kingston', imageUrl: 'images/jamaica.jpeg', isVisited: false },
    { id: 'JAPAN ', name: 'Japan', capital: 'Tokyo', imageUrl: 'images/japan.jpeg', isVisited: false },
    { id: 'JORDAN ', name: 'Jordan', capital: 'Amman', imageUrl: 'images/jordan.jpeg', isVisited: false },
    { id: 'KAZAKHSTAN ', name: 'Kazakhstan', capital: 'Nur-Sultan', imageUrl: 'images/kazakhstan.jpeg', isVisited: false },
    { id: 'KENYA ', name: 'Kenya', capital: 'Nairobi', imageUrl: 'images/kenya.jpeg', isVisited: false },
    { id: 'KIRIBATI ', name: 'Kiribati', capital: 'Tarawa Atoll', imageUrl: 'images/kiribati.jpeg', isVisited: false },
    { id: 'KOSOVO ', name: 'Kosovo', capital: 'Pristina', imageUrl: 'images/kosovo.jpeg', isVisited: false },
    { id: 'KUWAIT ', name: 'Kuwait', capital: 'Kuwait City', imageUrl: 'images/kuwait.jpeg', isVisited: false },
    { id: 'KYRGYZSTAN ', name: 'Krygyzstan', capital: 'Bishkek', imageUrl: 'images/kyrgyzstan.jpeg', isVisited: false },
    { id: 'LAOS ', name: 'Laos', capital: 'Vientiane', imageUrl: 'images/laos.jpeg', isVisited: false },
    { id: 'LATVIA ', name: 'Latvia', capital: 'Riga', imageUrl: 'images/latvia.jpeg', isVisited: false },
    { id: 'LEBANON ', name: 'Lebanon', capital: 'Beirut', imageUrl: 'images/lebanon.jpeg', isVisited: false },
    { id: 'LESOTHO ', name: 'Lesotho', capital: 'Maseru', imageUrl: 'images/lesotho.jpeg', isVisited: false },
    { id: 'LIBERIA ', name: 'Liberia', capital: 'Monrovia', imageUrl: 'images/liberia.jpeg', isVisited: false },
    { id: 'LIBYA ', name: 'Libya', capital: 'Tripoli', imageUrl: 'images/libya.jpeg', isVisited: false },
    { id: 'LIECHTENSTEIN ', name: 'Liechtenstein', capital: 'Vaduz', imageUrl: 'images/liechtenstein.jpeg', isVisited: false },
    { id: 'LITHUANIA ', name: 'Lithuania', capital: 'Vilnius', imageUrl: 'images/lithuania.jpeg', isVisited: false },
    { id: 'LUXEMBOURG ', name: 'Luxembourg', capital: 'Luxembourg', imageUrl: 'images/luxembourg.jpeg', isVisited: false },
    { id: 'MADAGASCAR ', name: 'Madagascar', capital: 'Antananarivo', imageUrl: 'images/madagascar.jpeg', isVisited: false },
    { id: 'MALAWI ', name: 'Malawi', capital: 'Lilongwe', imageUrl: 'images/malawi.jpeg', isVisited: false },
    { id: 'MALAYSIA ', name: 'Malaysia', capital: 'Kuala Lumpur', imageUrl: 'images/malaysia.jpeg', isVisited: true },
    { id: 'MALDIVES ', name: 'Maldives', capital: 'Male', imageUrl: 'images/maldives.jpeg', isVisited: false },
    { id: 'MALI ', name: 'Mali', capital: 'Bamako', imageUrl: 'images/mali.jpeg', isVisited: false },
    { id: 'MALTA ', name: 'Malta', capital: 'Valletta', imageUrl: 'images/malta.jpeg', isVisited: false },
    { id: 'MARSHALL_ISLANDS ', name: 'Marshall Islands', capital: 'Majuro', imageUrl: 'images/marshall_islands.jpeg', isVisited: false },
    { id: 'MAURITANIA ', name: 'Mauritania', capital: 'Nouakchott', imageUrl: 'images/mauritania.jpeg', isVisited: false },
    { id: 'MAURITIUS ', name: 'Mauritius', capital: 'Port Louis', imageUrl: 'images/mauritius.jpeg', isVisited: false },
    { id: 'MEXICO ', name: 'Mexico', capital: 'Mexico City', imageUrl: 'images/mexico.jpeg', isVisited: true },
    { id: 'MOLDOVA ', name: 'Moldova', capital: 'Chisinau', imageUrl: 'images/moldova.jpeg', isVisited: false },
    { id: 'MONACO ', name: 'Monaco', capital: 'Monaco', imageUrl: 'images/monaco.jpeg', isVisited: false },
    { id: 'MONGOLIA ', name: 'Mongolia', capital: 'Ulaanbaatar', imageUrl: 'images/mongolia.jpeg', isVisited: false },
    { id: 'MONTENEGRO ', name: 'Montenegro', capital: 'Podgorica', imageUrl: 'images/montenegro.jpeg', isVisited: false },
    { id: 'MOROCCO ', name: 'Morocco', capital: 'Rabat', imageUrl: 'images/morocco.jpeg', isVisited: false },
    { id: 'MOZAMBIQUE ', name: 'Mozambique', capital: 'Maputo', imageUrl: 'images/mozambique.jpeg', isVisited: false },
    { id: 'MYANMAR ', name: 'Myanmar (Burma)', capital: 'Nay Pyi Taw', imageUrl: 'images/myanmar.jpeg', isVisited: false },
    { id: 'NAMIBIA ', name: 'Namibia', capital: 'Windhoek', imageUrl: 'images/namibia.jpeg', isVisited: false },
    { id: 'NAURU ', name: 'Nauru', capital: 'No official Capital', imageUrl: 'images/nauru.jpeg', isVisited: false },
    { id: 'NEPAL ', name: 'Nepal', capital: 'Kathmandu', imageUrl: 'images/nepal.jpeg', isVisited: false },
    { id: 'NETHERLANDS ', name: 'Netherlands', capital: 'Amsterdam', imageUrl: 'images/netherlands.jpeg', isVisited: false },
    { id: 'NEW_ZEALAND ', name: 'New Zealand', capital: 'Wellington', imageUrl: 'images/new_zealand.jpeg', isVisited: false },
    { id: 'NICARAGUA ', name: 'Nicaragua', capital: 'Managua', imageUrl: 'images/nicaragua.jpeg', isVisited: false },
    { id: 'NIGER ', name: 'Niger', capital: 'Niamey', imageUrl: 'images/niger.jpeg', isVisited: false },
    { id: 'NIGERIA ', name: 'Nigeria', capital: 'Abuja', imageUrl: 'images/nigeria.jpeg', isVisited: false },
    { id: 'NORTH_KOREA ', name: 'North Korea', capital: 'Pyongyang', imageUrl: 'images/north_korea.jpeg', isVisited: false },
    { id: 'NORTH_MACEDONIA ', name: 'North Macedonia (Macedonia)', capital: 'Skopje',
      imageUrl: 'images/north_macedonia.jpeg', isVisited: false },
    { id: 'NORTHERN_ISLAND ', name: 'Northern Island', capital: 'Belfast', imageUrl: 'images/northern_island.jpeg', isVisited: false },
    { id: 'NORWAY ', name: 'Norway', capital: 'Oslo', imageUrl: 'images/norway.jpeg', isVisited: false },
    { id: 'OMAN ', name: 'Oman', capital: 'Muscat', imageUrl: 'images/oman.jpeg', isVisited: false },
    { id: 'PAKISTAN ', name: 'Pakistan', capital: 'Islamabad', imageUrl: 'images/pakistan.jpeg', isVisited: false },
    { id: 'PALAU ', name: 'Palau', capital: 'Melekeok', imageUrl: 'images/palau.jpeg', isVisited: false },
    { id: 'PANAMA ', name: 'Panam', capital: 'Panama City', imageUrl: 'images/panama.jpeg', isVisited: false },
    { id: 'PAPUA_NEW_GUINEA ', name: 'Papua New Guinea', capital: 'Port Moresby',
      imageUrl: 'images/papua_new_guinea.jpeg', isVisited: false },
    { id: 'PARAGUAY ', name: 'Paraguay', capital: 'Asuncion', imageUrl: 'images/paraguay.jpeg', isVisited: false },
    { id: 'PERU ', name: 'Peru', capital: 'Lima', imageUrl: 'images/peru.jpeg', isVisited: false },
    { id: 'PHILIPPINES ', name: 'Philippines', capital: 'Manila', imageUrl: 'images/philippines.jpeg', isVisited: false },
    { id: 'POLAND ', name: 'Poland', capital: 'Warsaw', imageUrl: 'images/poland.jpeg', isVisited: false },
    { id: 'PORTUGAL ', name: 'Portugal', capital: 'Lisbon', imageUrl: 'images/portugal.jpeg', isVisited: false },
    { id: 'QATAR ', name: 'Qatar', capital: 'Doha', imageUrl: 'images/qatar.jpeg', isVisited: false },
    { id: 'ROMANIA ', name: 'Romania', capital: 'Bucharest', imageUrl: 'images/romania.jpeg', isVisited: false },
    { id: 'RUSSIA ', name: 'Russia', capital: 'Moscow', imageUrl: 'images/russia.jpeg', isVisited: false },
    { id: 'RWANDA ', name: 'Rwanda', capital: 'Kigali', imageUrl: 'images/rwanda.jpeg', isVisited: false },
    { id: 'SAINT_KITTS_AND_NEVIS ', name: 'Saint Kitts and Nevis', capital: 'Basseterre',
      imageUrl: 'images/saint_kitts_and_nevis.jpeg', isVisited: false },
    { id: 'SAINT_LUCIA ', name: 'Saint Lucia', capital: 'Castries', imageUrl: 'images/saint_lucia.jpeg', isVisited: false },
    { id: 'SAINT_VINCENT_AND_THE_GRENADINES ', name: 'Saint Vincent and the Grenadines', capital: 'Kingstown',
      imageUrl: 'images/saint_vincent_and_the_grenadines.jpeg', isVisited: false },
    { id: 'SAMOA ', name: 'Samoa', capital: 'Apia', imageUrl: 'images/samao.jpeg', isVisited: false },
    { id: 'SAN_MARINO ', name: 'San Marino', capital: 'San Marino', imageUrl: 'images/san_marino.jpeg', isVisited: false },
    { id: 'SAO_TOME_AND_PRINCIPE ', name: 'Sao Tome and Principe', capital: 'Sao Tome',
      imageUrl: 'images/sao_tome_and_principe.jpeg', isVisited: false },
    { id: 'SAUDI_ARABIA ', name: 'Saudi Arabia', capital: 'Riyadh', imageUrl: 'images/saudi_arabia.jpeg', isVisited: false },
    { id: 'SCOTLAND ', name: 'Scotland', capital: 'Edinburgh', imageUrl: 'images/scotland.jpeg', isVisited: false },
    { id: 'SENEGAL ', name: 'Senegal', capital: 'Dakar', imageUrl: 'images/senegal.jpeg', isVisited: false },
    { id: 'SERBIA ', name: 'Serbia', capital: 'Belgrade', imageUrl: 'images/serbia.jpeg', isVisited: false },
    { id: 'SEYCHELLES ', name: 'Seychelles', capital: 'Victoria', imageUrl: 'images/seychelles.jpeg', isVisited: false },
    { id: 'SIERRA_TOWN ', name: 'Sierra Leone', capital: 'Freetown', imageUrl: 'images/sierra_town.jpeg', isVisited: false },
    { id: 'SINGAPORE', name: 'Singapore', capital: 'Singapore', imageUrl: 'images/singapore.jpeg', isVisited: false },
    { id: 'SLOVAKIA', name: 'Slovakia', capital: 'Bratislava', imageUrl: 'images/slovakia.jpeg', isVisited: false },
    { id: 'SLOVENIA ', name: 'Slovenia', capital: 'Ljubljana', imageUrl: 'images/slovenia.jpeg', isVisited: false },
    { id: 'SOLOMON_ISLANDS ', name: 'Solomon Islands', capital: 'Honiara', imageUrl: 'images/solomon_islands.jpeg', isVisited: false },
    { id: 'SOMALIA ', name: 'Somalia', capital: 'Mogadishu', imageUrl: 'images/somalia.jpeg', isVisited: false },
    { id: 'SOUTH_AFRICA ', name: 'South Africa', capital: 'Pretoria, Bloemfontein, Cape Town',
      imageUrl: 'images/south_africa.jpeg', isVisited: false },
    { id: 'SOUTH_KOREA ', name: 'South Korea', capital: 'Seoul', imageUrl: 'images/south_korea.jpeg', isVisited: false },
    { id: 'SOUTH_SUDAN ', name: 'South Sudan', capital: 'Juba', imageUrl: 'images/south_sudan.jpeg', isVisited: false },
    { id: 'SPAIN ', name: 'Spain', capital: 'Madrid', imageUrl: 'images/spain.jpeg', isVisited: false },
    { id: 'SRILANKA ', name: 'Sri Lanka', capital: 'Colombo', imageUrl: 'images/srilanka.jpeg', isVisited: false },
    { id: 'SUDAN ', name: 'Sudan', capital: 'Khartoum', imageUrl: 'images/sudan.jpeg', isVisited: false },
    { id: 'SURINAME ', name: 'Suriname', capital: 'Paramaribo', imageUrl: 'images/suriname.jpeg', isVisited: false },
    { id: 'SWEDEN ', name: 'Sweden', capital: 'Stockholm', imageUrl: 'images/sweden.jpeg', isVisited: false },
    { id: 'SWITZERLAND ', name: 'Switzerland', capital: 'Bern', imageUrl: 'images/switzerland.jpeg', isVisited: false },
    { id: 'SYRIA ', name: 'Syria', capital: 'Damascus', imageUrl: 'images/syria.jpeg', isVisited: false },
    { id: 'TAIWAN ', name: 'Taiwan', capital: 'Taipei', imageUrl: 'images/taiwan.jpeg', isVisited: false },
    { id: 'TAJIKISTAN ', name: 'Tajikistan', capital: 'Dushanbe', imageUrl: 'images/tajikistan.jpeg', isVisited: false },
    { id: 'TANZANIA ', name: 'Tanzania', capital: 'Dodoma', imageUrl: 'images/tanzania.jpeg', isVisited: false },
    { id: 'THAILAND ', name: 'Thailand', capital: 'Bangkok', imageUrl: 'images/thailand.jpeg', isVisited: false },
    { id: 'TOGO ', name: 'Togo', capital: 'Lome', imageUrl: 'images/togo.jpeg', isVisited: false },
    { id: 'TONGA ', name: 'Tonga', capital: 'Nuku\'alofa', imageUrl: 'images/tonga.jpeg', isVisited: false },
    { id: 'TRINIDAD_AND_TOBAGO ', name: 'Trinidad and Tobago', capital: 'Port of Spain',
      imageUrl: 'images/trindad_and_tobago.jpeg', isVisited: false },
    { id: 'TUNISIA ', name: 'Tunisia', capital: 'Tunis', imageUrl: 'images/tunisia.jpeg', isVisited: false },
    { id: 'TURKEY ', name: 'Turkey', capital: 'Ankara', imageUrl: 'images/turkey.jpeg', isVisited: false },
    { id: 'TURKMENISTAN ', name: 'Turkmenistan', capital: 'Ashgabat', imageUrl: 'images/turkmenistan.jpeg', isVisited: false },
    { id: 'TUVALU ', name: 'Tuvalu', capital: 'Funafuti', imageUrl: 'images/tuvalu.jpeg', isVisited: false },
    { id: 'UGANDA ', name: 'Uganda', capital: 'Kampala', imageUrl: 'images/uganda.jpeg', isVisited: false },
    { id: 'UKRAINE ', name: 'Ukraine', capital: 'Kiev', imageUrl: 'images/ukraine.jpeg', isVisited: false },
    { id: 'UNITED_ARAB_EMIRATES ', name: 'United Arab Emirates', capital: 'Abu Dhabi',
      imageUrl: 'images/united_arab_emirates.jpeg', isVisited: false },
    { id: 'UNITED_KINGDOM ', name: 'United Kingdom', capital: 'London', imageUrl: 'images/united_kingdom.jpeg', isVisited: false },
    { id: 'UNITED_STATES ', name: 'United States', capital: 'Washington D.C.', imageUrl: 'images/united_states.jpeg', isVisited: true },
    { id: 'URUGUAY ', name: 'Uruguay', capital: 'Montevideo', imageUrl: 'images/uruguay.jpeg', isVisited: false },
    { id: 'UZBEKISTAN ', name: 'Uzbekistan', capital: 'Tashkent', imageUrl: 'images/uzbekistan.jpeg', isVisited: false },
    { id: 'VANUATU ', name: 'Vanuatu', capital: 'Port Vila', imageUrl: 'images/vanuatu.jpeg', isVisited: false },
    { id: 'VATICAN_CITY ', name: 'Vatican City', capital: 'Vatican City', imageUrl: 'images/vatican_city.jpeg', isVisited: false },
    { id: 'VENEZUELA ', name: 'Venezuela', capital: 'Caracas', imageUrl: 'images/venezuela.jpeg', isVisited: false },
    { id: 'VIETNAM ', name: 'Vietnam', capital: 'Hanoi', imageUrl: 'images/vietnam.jpeg', isVisited: false },
    { id: 'WALES ', name: 'Wales', capital: 'Cardiff', imageUrl: 'images/wales.jpeg', isVisited: false },
    { id: 'YEMEN ', name: 'Yemen', capital: 'Sana\'a', imageUrl: 'images/yemen.jpeg', isVisited: false },
    { id: 'ZAMBIA ', name: 'Zambia', capital: 'Lusaka', imageUrl: 'images/zambia.jpeg', isVisited: false },
    { id: 'ZIMBABWE ', name: 'Zimbabwe', capital: 'Harare', imageUrl: 'images/zimbabwe.jpeg', isVisited: false },
];
